(function () {
  var baseJobs = [
    {
      id: 'job-1',
      title: 'SDE Intern',
      company: 'Amazon India',
      location: 'Bangalore',
      mode: 'Hybrid',
      experience: 'Fresher',
      skills: ['Java', 'Data Structures', 'Algorithms'],
      source: 'LinkedIn',
      postedDaysAgo: 1,
      salaryRange: '₹15k–₹40k/month Internship',
      applyUrl: 'https://www.amazon.jobs/en/jobs/sde-intern-bangalore',
      description: 'Work with senior engineers to design and build customer-facing services for Amazon India.\nCollaborate with cross-functional teams to understand requirements and translate them into technical tasks.\nParticipate in code reviews, write unit tests, and follow best practices for maintainable code.\nThis role is ideal for final-year students who want hands-on experience in large scale distributed systems.'
    },
    {
      id: 'job-2',
      title: 'Graduate Engineer Trainee',
      company: 'Infosys',
      location: 'Mysore',
      mode: 'Onsite',
      experience: 'Fresher',
      skills: ['Java', 'SQL', 'Object-Oriented Programming'],
      source: 'Naukri',
      postedDaysAgo: 3,
      salaryRange: '3–5 LPA',
      applyUrl: 'https://careers.infosys.com/graduate-engineer-trainee',
      description: 'Join the Infosys global delivery team as a Graduate Engineer Trainee.\nYou will go through structured training on Java, databases, and core engineering fundamentals.\nPost training, you will be deployed to live projects with mentorship from senior team members.\nAn excellent opportunity for fresh graduates to build a long-term career in consulting and technology.'
    },
    {
      id: 'job-3',
      title: 'Junior Backend Developer',
      company: 'Razorpay',
      location: 'Bangalore',
      mode: 'Hybrid',
      experience: '1-3',
      skills: ['Node.js', 'PostgreSQL', 'REST APIs'],
      source: 'LinkedIn',
      postedDaysAgo: 0,
      salaryRange: '6–10 LPA',
      applyUrl: 'https://razorpay.com/careers/junior-backend-developer',
      description: 'Work on payment processing services that handle high transaction volumes every day.\nDesign, build, and maintain microservices with a focus on reliability and performance.\nCollaborate with product and frontend teams to deliver clear, well-documented APIs.\nIdeal for developers who have some production experience and want to deepen their backend skills.'
    },
    {
      id: 'job-4',
      title: 'Frontend Intern',
      company: 'Swiggy',
      location: 'Bangalore',
      mode: 'Remote',
      experience: 'Fresher',
      skills: ['React', 'TypeScript', 'CSS'],
      source: 'LinkedIn',
      postedDaysAgo: 2,
      salaryRange: '₹15k–₹40k/month Internship',
      applyUrl: 'https://careers.swiggy.com/frontend-intern',
      description: 'Support the consumer web team in building responsive and accessible user interfaces.\nWork with design and product to translate Figma files into clean, performant React components.\nLearn industry practices for code reviews, testing, and frontend observability.\nSuitable for students with strong fundamentals in JavaScript and modern UI development.'
    },
    {
      id: 'job-5',
      title: 'QA Intern',
      company: 'Flipkart',
      location: 'Bangalore',
      mode: 'Hybrid',
      experience: 'Fresher',
      skills: ['Manual Testing', 'Test Cases', 'Basic SQL'],
      source: 'Naukri',
      postedDaysAgo: 4,
      salaryRange: '₹15k–₹40k/month Internship',
      applyUrl: 'https://www.flipkartcareers.com/qa-intern',
      description: 'Assist the quality engineering team in validating new features before release.\nWrite and execute detailed test cases across web and mobile applications.\nReport bugs with clear reproduction steps and work closely with developers on fixes.\nIdeal for candidates who are detail-oriented and interested in a career in quality engineering.'
    },
    {
      id: 'job-6',
      title: 'Data Analyst Intern',
      company: 'Freshworks',
      location: 'Chennai',
      mode: 'Hybrid',
      experience: 'Fresher',
      skills: ['Excel', 'SQL', 'Data Visualization'],
      source: 'LinkedIn',
      postedDaysAgo: 5,
      salaryRange: '₹15k–₹40k/month Internship',
      applyUrl: 'https://www.freshworks.com/company/careers/data-analyst-intern',
      description: 'Work with the analytics team to track product usage and customer behaviour.\nBuild dashboards and basic reports to help stakeholders make data-driven decisions.\nLearn how to write efficient SQL queries and apply analytical thinking to real datasets.\nThis internship is a good fit for students with strong quantitative skills.'
    },
    {
      id: 'job-7',
      title: 'Java Developer (0-1)',
      company: 'TCS',
      location: 'Pune',
      mode: 'Onsite',
      experience: '0-1',
      skills: ['Java', 'Spring Boot', 'REST'],
      source: 'Naukri',
      postedDaysAgo: 6,
      salaryRange: '3–5 LPA',
      applyUrl: 'https://careers.tcs.com/java-developer-0-1',
      description: 'Contribute to enterprise applications built on Java and Spring Boot.\nFix bugs, implement small features, and participate in regular code reviews.\nYou will work within an experienced team that values clarity, maintainability, and testing.\nIdeal for engineers with up to one year of experience and strong Java fundamentals.'
    },
    {
      id: 'job-8',
      title: 'Python Developer (Fresher)',
      company: 'Wipro',
      location: 'Hyderabad',
      mode: 'Hybrid',
      experience: 'Fresher',
      skills: ['Python', 'Django', 'REST APIs'],
      source: 'Naukri',
      postedDaysAgo: 2,
      salaryRange: '3–5 LPA',
      applyUrl: 'https://careers.wipro.com/python-developer-fresher',
      description: 'Join a delivery team building internal tools and integration services using Python.\nLearn to work with Django, REST APIs, and relational databases in a production setup.\nYou will be guided by senior engineers and follow a clear review and release process.\nBest suited for fresh graduates who enjoy backend development with Python.'
    },
    {
      id: 'job-9',
      title: 'React Developer (1-3)',
      company: 'Zoho',
      location: 'Chennai',
      mode: 'Onsite',
      experience: '1-3',
      skills: ['React', 'JavaScript', 'HTML', 'CSS'],
      source: 'LinkedIn',
      postedDaysAgo: 3,
      salaryRange: '6–10 LPA',
      applyUrl: 'https://careers.zoho.com/react-developer',
      description: 'Build and maintain web interfaces for Zoho\u2019s business applications.\nWork closely with designers to implement clean, accessible UI components.\nCollaborate with backend teams to integrate APIs and handle state effectively.\nIdeal for developers who value performance, clarity, and simple user flows.'
    },
    {
      id: 'job-10',
      title: 'SDE Intern',
      company: 'CRED',
      location: 'Bangalore',
      mode: 'Remote',
      experience: 'Fresher',
      skills: ['Go', 'Distributed Systems', 'APIs'],
      source: 'LinkedIn',
      postedDaysAgo: 0,
      salaryRange: '₹15k–₹40k/month Internship',
      applyUrl: 'https://careers.cred.club/sde-intern',
      description: 'Work within a small engineering pod on features that ship to production.\nHelp build services that are reliable, observable, and easy to operate.\nYou will pair with experienced engineers and learn how to reason about trade-offs.\nSuited for students who enjoy backend systems and thoughtful engineering.'
    },
    {
      id: 'job-11',
      title: 'Graduate Engineer Trainee',
      company: 'Capgemini',
      location: 'Mumbai',
      mode: 'Hybrid',
      experience: 'Fresher',
      skills: ['Java', 'Spring', 'SQL'],
      source: 'Naukri',
      postedDaysAgo: 7,
      salaryRange: '3–5 LPA',
      applyUrl: 'https://www.capgemini.com/in-en/careers/graduate-engineer-trainee',
      description: 'Start your consulting journey with Capgemini India as a Graduate Engineer.\nGo through structured training on enterprise technologies and delivery practices.\nYou will be placed on client projects after completing internal certifications.\nA steady path for freshers who want exposure to multiple domains.'
    },
    {
      id: 'job-12',
      title: 'Junior Backend Developer',
      company: 'Juspay',
      location: 'Bangalore',
      mode: 'Remote',
      experience: '1-3',
      skills: ['Kotlin', 'Functional Programming', 'Microservices'],
      source: 'LinkedIn',
      postedDaysAgo: 4,
      salaryRange: '6–10 LPA',
      applyUrl: 'https://juspay.in/careers/junior-backend-developer',
      description: 'Work on payment infrastructure that powers millions of daily transactions.\nUse modern languages and functional programming concepts in production systems.\nCollaborate with a small team that values correctness and simplicity.\nBest suited for engineers who enjoy deep technical work and clean abstractions.'
    },
    {
      id: 'job-13',
      title: 'Frontend Intern',
      company: 'PhonePe',
      location: 'Bangalore',
      mode: 'Hybrid',
      experience: 'Fresher',
      skills: ['React', 'TypeScript', 'Testing'],
      source: 'LinkedIn',
      postedDaysAgo: 6,
      salaryRange: '₹15k–₹40k/month Internship',
      applyUrl: 'https://phonepe.com/careers/frontend-intern',
      description: 'Help build and refine user journeys on the PhonePe web experience.\nWork with design systems, component libraries, and performance budgets.\nShadow senior engineers to learn about monitoring and progressive rollouts.\nIdeal for interns who care about both design and engineering detail.'
    },
    {
      id: 'job-14',
      title: 'QA Intern',
      company: 'Paytm',
      location: 'Noida',
      mode: 'Onsite',
      experience: 'Fresher',
      skills: ['Test Planning', 'Regression Testing', 'Automation Basics'],
      source: 'Naukri',
      postedDaysAgo: 5,
      salaryRange: '₹15k–₹40k/month Internship',
      applyUrl: 'https://paytm.com/careers/qa-intern',
      description: 'Support the test engineering team across multiple Paytm products.\nDesign and execute regression suites for web and mobile applications.\nLearn how to use automation tools alongside thoughtful manual testing.\nGood for detail-focused graduates exploring a QA career path.'
    },
    {
      id: 'job-15',
      title: 'Data Analyst Intern',
      company: 'Cognizant',
      location: 'Kolkata',
      mode: 'Hybrid',
      experience: 'Fresher',
      skills: ['SQL', 'Power BI', 'Reporting'],
      source: 'Indeed',
      postedDaysAgo: 8,
      salaryRange: '₹15k–₹40k/month Internship',
      applyUrl: 'https://careers.cognizant.com/data-analyst-intern',
      description: 'Work with consulting teams to prepare client-ready analytical reports.\nTranslate raw data into structured insights using SQL and BI tools.\nGain exposure to common business metrics across industries.\nSuitable for analytical graduates who enjoy working with numbers and trends.'
    },
    {
      id: 'job-16',
      title: 'Java Developer (0-1)',
      company: 'IBM India',
      location: 'Pune',
      mode: 'Hybrid',
      experience: '0-1',
      skills: ['Java', 'Spring Boot', 'REST APIs'],
      source: 'LinkedIn',
      postedDaysAgo: 9,
      salaryRange: '6–10 LPA',
      applyUrl: 'https://www.ibm.com/careers/java-developer-0-1',
      description: 'Join IBM\u2019s application development team focusing on enterprise clients.\nImplement features, fix defects, and contribute to technical documentation.\nWork within an agile environment with regular sprint rituals.\nIdeal for early-career developers looking for structured growth.'
    },
    {
      id: 'job-17',
      title: 'Python Developer (Fresher)',
      company: 'Oracle India',
      location: 'Bangalore',
      mode: 'Onsite',
      experience: 'Fresher',
      skills: ['Python', 'Flask', 'SQL'],
      source: 'LinkedIn',
      postedDaysAgo: 7,
      salaryRange: '3–5 LPA',
      applyUrl: 'https://careers.oracle.com/python-developer-fresher',
      description: 'Contribute to internal tooling and automation projects built on Python.\nCollaborate with senior engineers to design clean, maintainable modules.\nLearn how large engineering teams structure code, reviews, and releases.\nSuitable for fresh graduates who are comfortable with Python basics.'
    },
    {
      id: 'job-18',
      title: 'React Developer (1-3)',
      company: 'Freshdesk Labs',
      location: 'Chennai',
      mode: 'Hybrid',
      experience: '1-3',
      skills: ['React', 'TypeScript', 'Design Systems'],
      source: 'Indeed',
      postedDaysAgo: 2,
      salaryRange: '10–18 LPA',
      applyUrl: 'https://jobs.freshdesk.com/react-developer',
      description: 'Implement new product features on top of a shared design system.\nPair closely with designers to ensure a calm, predictable user experience.\nFocus on performance, accessibility, and clean component boundaries.\nGreat for engineers who appreciate thoughtful UI engineering.'
    },
    {
      id: 'job-19',
      title: 'Junior Backend Developer',
      company: 'LambdaStack Labs',
      location: 'Remote',
      mode: 'Remote',
      experience: '1-3',
      skills: ['Node.js', 'MongoDB', 'Microservices'],
      source: 'LinkedIn',
      postedDaysAgo: 1,
      salaryRange: '6–10 LPA',
      applyUrl: 'https://careers.lambdastacklabs.com/junior-backend-developer',
      description: 'Join a remote-first startup building APIs for SaaS integrations.\nShip small, frequent changes with strong code review culture.\nWork closely with founders to understand how product decisions are made.\nIdeal for engineers who enjoy autonomy and clear ownership.'
    },
    {
      id: 'job-20',
      title: 'SDE Intern',
      company: 'Northstar Fintech',
      location: 'Bangalore',
      mode: 'Onsite',
      experience: 'Fresher',
      skills: ['Java', 'Kotlin', 'SQL'],
      source: 'LinkedIn',
      postedDaysAgo: 10,
      salaryRange: '₹15k–₹40k/month Internship',
      applyUrl: 'https://jobs.northstarfintech.com/sde-intern',
      description: 'Work with the core banking integrations team at a fast-growing fintech startup.\nAssist in writing clear, well-tested services that interact with financial partners.\nLearn how to operate services in production with observability in place.\nPerfect for interns who want a mix of startup pace and engineering discipline.'
    }
  ];

  var expandedJobs = [];

  for (var i = 0; i < 3; i++) {
    for (var j = 0; j < baseJobs.length; j++) {
      var original = baseJobs[j];
      var clone = {
        id: original.id + '-v' + (i + 1),
        title: original.title,
        company: original.company,
        location: original.location,
        mode: original.mode,
        experience: original.experience,
        skills: original.skills.slice(),
        source: original.source,
        postedDaysAgo: (original.postedDaysAgo + i) % 11,
        salaryRange: original.salaryRange,
        applyUrl: original.applyUrl,
        description: original.description
      };
      expandedJobs.push(clone);
    }
  }

  window.JOB_NOTIFICATION_DATA = expandedJobs;
})();

